const SYSTEM_ROLES = { SYSTEM_ADMIN: 'SYSTEM_ADMIN', MEMBER: 'MEMBER' };

const ORG_ROLES = { COMPANY_ADMIN: 'COMPANY_ADMIN', MANAGER: 'MANAGER', MEMBER: 'MEMBER' };

const AGENT_TYPES = {
  CALL_CENTER: 'CALL_CENTER', SALES: 'SALES', SUPPORT: 'SUPPORT',
  BOOKING: 'BOOKING', MARKETING: 'MARKETING', CUSTOM: 'CUSTOM',
};

const AGENT_STATUSES = { ACTIVE: 'ACTIVE', IDLE: 'IDLE', OFFLINE: 'OFFLINE', MAINTENANCE: 'MAINTENANCE' };

const CONNECTION_STATUSES = {
  CONNECTED: 'CONNECTED', DISCONNECTED: 'DISCONNECTED', ERROR: 'ERROR',
  PAUSED: 'PAUSED', PENDING_SETUP: 'PENDING_SETUP',
};

const AGENT_PROVIDERS = {
  WHATSAPP_BOT: 'WHATSAPP_BOT', MESSENGER_BOT: 'MESSENGER_BOT',
  WEBSITE_CHATBOT: 'WEBSITE_CHATBOT', VOICE_AGENT: 'VOICE_AGENT',
  EMAIL_BOT: 'EMAIL_BOT', CUSTOM_API: 'CUSTOM_API',
  DEMO_CHANNEL: 'DEMO_CHANNEL', OTHER: 'OTHER',
};

const CHANNELS = ['WhatsApp', 'Messenger', 'Website Chat', 'Voice', 'Email', 'Custom API', 'Demo', 'Other'];

const EVENT_TYPES = {
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED', MESSAGE_SENT: 'MESSAGE_SENT',
  TASK_STARTED: 'TASK_STARTED', TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_FAILED: 'TASK_FAILED', OUTPUT_GENERATED: 'OUTPUT_GENERATED',
  STATUS_CHANGE: 'STATUS_CHANGE', ERROR: 'ERROR', CUSTOM: 'CUSTOM',
};

const EVENT_STATUSES = { RECEIVED: 'RECEIVED', PROCESSED: 'PROCESSED', FAILED: 'FAILED' };

const REVIEW_STATUSES = {
  PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED',
  EDITED: 'EDITED', SENT: 'SENT',
};

const TASK_STATUSES = {
  TODO: 'TODO', IN_PROGRESS: 'IN_PROGRESS', DONE: 'DONE',
  CANCELLED: 'CANCELLED', FAILED: 'FAILED', PENDING_REVIEW: 'PENDING_REVIEW',
};

const PRIORITIES = { LOW: 'LOW', MEDIUM: 'MEDIUM', HIGH: 'HIGH', URGENT: 'URGENT' };

const CUSTOMER_STATUSES = {
  LEAD: 'LEAD', PROSPECT: 'PROSPECT', ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE', CHURNED: 'CHURNED',
};

const PAGINATION = { DEFAULT_LIMIT: 20, MAX_LIMIT: 100 };

module.exports = {
  SYSTEM_ROLES, ORG_ROLES, AGENT_TYPES, AGENT_STATUSES,
  CONNECTION_STATUSES, AGENT_PROVIDERS, CHANNELS,
  EVENT_TYPES, EVENT_STATUSES, REVIEW_STATUSES,
  TASK_STATUSES, PRIORITIES, CUSTOMER_STATUSES, PAGINATION,
};
